### ISSUE TITLE
Call to undefined method SplFileObject::fread()

### ISSUE THREAD

**Issue by gnugat** [jolicode/php7-checker#1]
Hi, that's a nice project you have here!

I'd like to try it out, so I've cloned it locally:

```
git clone https://github.com/jolicode/php7-checker.git
cd php7-checker
composer install --no-dev -o
```

Then I've tried to run it:

```
bin/php7-checker src
```

Unfortunately, I run into the following error:

```
Checking php7-checker/src/
Parsing file 1/21PHP Fatal error:  Call to undefined method SplFileObject::fread() in php7-checker/src/Parser.php on line 76
```

Has this issue been fixed in a branch?

**Comment by pyrech** [comment]
Huu my bad, it looks like this is a PHP >=5.5 method :(

**Comment by gnugat** [comment]
I'm currently running PHP 5.5.9-1ubuntu4.11, maybe this method has been added in PHP 5.6?

**Comment by bastnic** [comment]
Yep, >= 5.5.11, see http://php.net/manual/en/splfileobject.fread.php

**Comment by gnugat** [comment]
Ha, it's been added in PHP 5.5.**11**... http://php.net/manual/en/splfileobject.fread.php

**Comment by gnugat** [comment]
Should I create a PR to update `composer.json` with this constraint?

**Comment by pyrech** [comment]
I thought to refactore this part a bit to get ride of the SplFileObject::fread() method instead ;)

**Comment by pyrech** [comment]
It should be ok now.
Thanks @gnugat for giving a try to this tool and reporting the issue! :beers:

**Comment by gnugat** [comment]
Cheers!
